// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIL9SNCNb4QhknN_D5GyrstjQ5CJyo32c',
    appId: '1:213069439182:web:ce8d3cdc36c2725b21b09f',
    messagingSenderId: '213069439182',
    projectId: 'task-manager-78635',
    authDomain: 'task-manager-78635.firebaseapp.com',
    databaseURL: 'https://task-manager-78635-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-manager-78635.firebasestorage.app',
    measurementId: 'G-26WGXHHS37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARkLoKSFBUCif4wG7701gMj7ZaeRipdPw',
    appId: '1:213069439182:android:305f0f8fcc0c132b21b09f',
    messagingSenderId: '213069439182',
    projectId: 'task-manager-78635',
    databaseURL: 'https://task-manager-78635-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-manager-78635.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfFWIOt8eW5j0M9vy6UlMQfE66qRy10PM',
    appId: '1:213069439182:ios:d0fb8b754d41e00421b09f',
    messagingSenderId: '213069439182',
    projectId: 'task-manager-78635',
    databaseURL: 'https://task-manager-78635-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-manager-78635.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfFWIOt8eW5j0M9vy6UlMQfE66qRy10PM',
    appId: '1:213069439182:ios:d0fb8b754d41e00421b09f',
    messagingSenderId: '213069439182',
    projectId: 'task-manager-78635',
    databaseURL: 'https://task-manager-78635-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-manager-78635.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIL9SNCNb4QhknN_D5GyrstjQ5CJyo32c',
    appId: '1:213069439182:web:8d2e98ab3f0b1a9421b09f',
    messagingSenderId: '213069439182',
    projectId: 'task-manager-78635',
    authDomain: 'task-manager-78635.firebaseapp.com',
    databaseURL: 'https://task-manager-78635-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-manager-78635.firebasestorage.app',
    measurementId: 'G-8KTS2ED044',
  );
}
